### ISSUE TITLE
为什么我运行和截图不一样？

### ISSUE THREAD

**Issue by HuJianChong** [kateLee/RecyclerViewLayout#1]

**Comment by kateLee** [comment]
請問你指的是什麼？希望可以明確地描述問題，比如是哪張截圖，哪個功能。

如果是指元件（ widget ）的外形（ style ）（例： ProgressBar ），這和該機型廠商和系統的版本有關。

**Comment by HuJianChong** [comment]
![test](https://cloud.githubusercontent.com/assets/7711020/7976219/dc6eb39c-0aaa-11e5-85b4-ee0f9aa3be9a.png)
我下拉都是这种效果，下面不会跟着滑动，请问是为什么？

**Comment by kateLee** [comment]
看起來不完全是我的範例？
是修改過的嗎？我按照提供的圖用了 google 提供的模擬器 Nexus one api15 執行是正常的。
我的範例示範兩種用法，分別是1.使用者滑動時，頁首自動隱藏。2.視差滾動。

下拉時，你預期他會滾動是表示上面還有資料？
因為看起來比較像是範例的第一種用法，那麼上面已經沒有資料，只有上滑會隱藏頁首，下滑時頁首會再次出現。

目前本元件的下拉更新效果來自 android 的 [SwipeRefreshLayout](https://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout.html) 。
